[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
