version: 2
jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build blog
          command: |
            docker create -v /blog --name blog alpine:3.7 /bin/true
            docker cp . blog:/blog
            docker run --volumes-from blog --name builder \
            thomasjpfan/pelican-blog-builder:1.0.2 make publish
      - run:
          name: Copy output
          command: docker cp blog:/blog/output .
      - run:
          name: Clean up
          command: docker container rm blog builder
          when: always
      - deploy:
          name: Rsync to server
          command: |
            apk --update add rsync
            rsync -e "ssh -p ${SSH_PORT} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
            -P -rvz --delete output/ "${SSH_USER}@${SSH_HOST}:${SSH_TARGET_DIR}" --cvs-exclude
